server:
  port: ${PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/toeic}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
      data-locations: classpath:db/migration/V2__init_schema.sql
      separator: ";;"
      encoding: UTF-8
      continue-on-error: true
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration-ms: 3600000 # 1 hour
  refresh-token-expiration-ms: 604800000 # 7 days
